# Generated by Django 6.0.1 on 2026-09-23 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='administrativeauditlog',
            name='action',
            field=models.CharField(choices=[('professional.approved', 'Profissional aprovado'), ('professional.access_revoked', 'Acesso de profissional retirado'), ('normative_version.created', 'Versão normativa criada'), ('normative_version.prepared', 'Versão normativa preparada'), ('normative_version.activated', 'Versão normativa ativada'), ('normative_test.synthetic_batch_created', 'Batch normativo sintético criado'), ('normative_test.cleared', 'Ambiente normativo de teste limpo')], db_index=True, max_length=64, verbose_name='ação'),
        ),
        migrations.AlterField(
            model_name='administrativeauditlog',
            name='object_type',
            field=models.CharField(choices=[('professional', 'Profissional'), ('normative_version', 'Versão normativa'), ('normative_test', 'Ambiente normativo de teste')], db_index=True, max_length=64, verbose_name='tipo de objeto'),
        ),
    ]
