import os
import sys
import django

sys.path.append(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
os.environ.setdefault("DJANGO_SETTINGS_MODULE", "hitop2.settings")
django.setup()

from polls.models import Spectra, Subfactor, Scale, Question

spectra_list = [
    "Detachment",
    "Externalizing",
    "Internalizing",
    "Somatoform",
    "Thought Disorder",
    "Catch",
]

spectra = {}
for name in spectra_list:
    spectra_obj, created = Spectra.objects.get_or_create(name=name)
    spectra[name] = spectra_obj

subfactor_list = [
    {"name": "Detachment", "spectra": "Detachment"},

    {"name": "Anankastia", "spectra": "Externalizing"},
    {"name": "Antagonism", "spectra": "Externalizing"},
    {"name": "Antisocial", "spectra": "Externalizing"},
    {"name": "Disinhibition", "spectra": "Externalizing"},
    {"name": "Harmful Substance Use", "spectra": "Externalizing"},

    {"name": "Distress", "spectra": "Internalizing"},
    {"name": "Eating Pathology", "spectra": "Internalizing"},
    {"name": "Fear", "spectra": "Internalizing"},
    {"name": "Sexual Problems", "spectra": "Internalizing"},

    {"name": "Somatoform", "spectra": "Somatoform"},

    {"name": "Thought Disorder", "spectra": "Thought Disorder"},
    {"name": "Mania", "spectra": "Thought Disorder"},

    {"name": "Catch", "spectra": "Catch"},
]

subfactor = {}
for s in subfactor_list:
    spectra_obj = spectra[s["spectra"]]
    subfactor_obj, created = Subfactor.objects.get_or_create(name=s["name"], spectra=spectra_obj)
    subfactor[s["name"]] = subfactor_obj

scale_list = [
    {"name": "Restricted Affectivity", "subfactor": "Detachment"},
    {"name": "Romantic Disinterest", "subfactor": "Detachment"},
    {"name": "Social Aloofness", "subfactor": "Detachment"},
    {"name": "Social Anxiety", "subfactor": "Detachment"},
    {"name": "Submissiveness", "subfactor": "Detachment"},
    {"name": "Well-being", "subfactor": "Detachment"},

    {"name": "Hyperdeliberation", "subfactor": "Anankastia"},
    {"name": "Perfectionism", "subfactor": "Anankastia"},
    {"name": "Rigidity", "subfactor": "Anankastia"},
    {"name": "Risk Aversion", "subfactor": "Anankastia"},
    {"name": "Workaholism", "subfactor": "Anankastia"},

    {"name": "Callousness", "subfactor": "Antagonism"},
    {"name": "Dishonesty - Deceitfulness", "subfactor": "Antagonism"},
    {"name": "Dishonesty - Manipulativeness", "subfactor": "Antagonism"},
    {"name": "Domineering", "subfactor": "Antagonism"},
    {"name": "Entitlement", "subfactor": "Antagonism"},
    {"name": "Exhibitionism", "subfactor": "Antagonism"},
    {"name": "Grandiosity", "subfactor": "Antagonism"},
    {"name": "Social Aggression", "subfactor": "Antagonism"},

    {"name": "Antisocial Behavior", "subfactor": "Antisocial"},
    {"name": "Oppositionality", "subfactor": "Antisocial"},

    {"name": "Disorganization", "subfactor": "Disinhibition"},
    {"name": "Gambling", "subfactor": "Disinhibition"},
    {"name": "Gaming", "subfactor": "Disinhibition"},
    {"name": "Non-persistence", "subfactor": "Disinhibition"},
    {"name": "Non-planfulness", "subfactor": "Disinhibition"},
    {"name": "Problematic Shopping", "subfactor": "Disinhibition"},
    {"name": "Restlessness", "subfactor": "Disinhibition"},
    {"name": "Risk Taking", "subfactor": "Disinhibition"},

    {"name": "Craving", "subfactor": "Harmful Substance Use"},
    {"name": "Hazardous Use", "subfactor": "Harmful Substance Use"},
    {"name": "Impaired Control", "subfactor": "Harmful Substance Use"},
    {"name": "Role Interference", "subfactor": "Harmful Substance Use"},
    {"name": "Tolerance", "subfactor": "Harmful Substance Use"},
    {"name": "Withdrawal", "subfactor": "Harmful Substance Use"},

    {"name": "Cognitive Problems", "subfactor": "Distress"},
    {"name": "Distress - Dysphoria (Anhedonia)", "subfactor": "Distress"},
    {"name": "Distress - Dysphoria (Anxious Worry)", "subfactor": "Distress"},
    {"name": "Distress - Dysphoria (Depressed Mood)", "subfactor": "Distress"},
    {"name": "Distress - Dysphoria (Lassitude)", "subfactor": "Distress"},
    {"name": "Distress - Dysphoria (Shame/Guilt)", "subfactor": "Distress"},
    {"name": "Emotionality (Affective Lability)", "subfactor": "Distress"},
    {"name": "Emotionality (Angry Hostility)", "subfactor": "Distress"},
    {"name": "Emotionality (Irritability)", "subfactor": "Distress"},
    {"name": "Insomnia", "subfactor": "Distress"},
    {"name": "Nightmares", "subfactor": "Distress"},
    {"name": "NSSI", "subfactor": "Distress"},
    {"name": "Suicidality", "subfactor": "Distress"},

    {"name": "Appetite Loss", "subfactor": "Eating Pathology"},
    {"name": "Binge Eating", "subfactor": "Eating Pathology"},
    {"name": "Body Dissatisfaction", "subfactor": "Eating Pathology"},
    {"name": "Body Focus", "subfactor": "Eating Pathology"},
    {"name": "Dietary Restraint", "subfactor": "Eating Pathology"},
    {"name": "Excessive Exercise", "subfactor": "Eating Pathology"},
    {"name": "Food Selectivity", "subfactor": "Eating Pathology"},
    {"name": "Muscle Building", "subfactor": "Eating Pathology"},
    {"name": "Purging", "subfactor": "Eating Pathology"},
    {"name": "Restricted Eating", "subfactor": "Eating Pathology"},

    {"name": "Agoraphobia", "subfactor": "Fear"},
    {"name": "Checking", "subfactor": "Fear"},
    {"name": "Cleaning", "subfactor": "Fear"},
    {"name": "Counting", "subfactor": "Fear"},
    {"name": "Excoriation", "subfactor": "Fear"},
    {"name": "Hoarding", "subfactor": "Fear"},
    {"name": "Hypervigilance", "subfactor": "Fear"},
    {"name": "Panic", "subfactor": "Fear"},
    {"name": "Specific Phobia (Animal-insect)", "subfactor": "Fear"},
    {"name": "Specific Phobia (Blood-Injection)", "subfactor": "Fear"},
    {"name": "Specific Phobia (situational)", "subfactor": "Fear"},
    {"name": "Trauma Reactions", "subfactor": "Fear"},
    {"name": "Trichotillomania", "subfactor": "Fear"},

    {"name": "Difficulties Reaching Orgasm", "subfactor": "Sexual Problems"},
    {"name": "Low Sexual Arousal", "subfactor": "Sexual Problems"},
    {"name": "Low Sexual Interest", "subfactor": "Sexual Problems"},
    {"name": "Paraphilias", "subfactor": "Sexual Problems"},
    {"name": "Premature Orgasm", "subfactor": "Sexual Problems"},
    {"name": "Risky Sex", "subfactor": "Sexual Problems"},
    {"name": "Sex-Related Substance Use", "subfactor": "Sexual Problems"},
    {"name": "Sexual Distress", "subfactor": "Sexual Problems"},
    {"name": "Sexual Pain", "subfactor": "Sexual Problems"},

    {"name": "Health Anxiety", "subfactor": "Somatoform"},
    {"name": "Somatic Preoccupation", "subfactor": "Somatoform"},
    {"name": "Conversion Symptoms", "subfactor": "Somatoform"},
    {"name": "Disease Conviction", "subfactor": "Somatoform"},
    {"name": "Bodily Distress", "subfactor": "Somatoform"},

    {"name": "Dissociation", "subfactor": "Thought Disorder"},
    {"name": "Eccentricity", "subfactor": "Thought Disorder"},
    {"name": "Fantasy Proneness", "subfactor": "Thought Disorder"},
    {"name": "Mistrust (Cynicism)", "subfactor": "Thought Disorder"},
    {"name": "Mistrust (Suspiciousness)", "subfactor": "Thought Disorder"},
    {"name": "Reality Distortion (Delusions)", "subfactor": "Thought Disorder"},
    {"name": "Reality Distortion (Hallucinations)", "subfactor": "Thought Disorder"},

    {"name": "Manic Energy", "subfactor": "Mania"},

    {"name": "Catch", "subfactor": "Catch"},
]

scale = {}
for s in scale_list:
    subfactor_obj = subfactor[s["subfactor"]]
    scale_obj, created = Scale.objects.get_or_create(name=s["name"], subfactor=subfactor_obj)
    scale[s["name"]] = scale_obj

questions_data =[
    {"scale": "Agoraphobia", "item_code": "hitop_156", "question_text": "Senti que não seria capaz de respirar num espaço pequeno, apertado ou fechado."},
    {"scale": "Agoraphobia", "item_code": "hitop_157", "question_text": "Tive medo de ficar preso/a no meio de uma multidão."},
    {"scale": "Agoraphobia", "item_code": "hitop_158", "question_text": "Evitei espaços pequenos, apertados ou fechados."},
    {"scale": "Agoraphobia", "item_code": "hitop_160", "question_text": "Evitei espaços públicos pequenos (como um escritório ou restaurante)."},
    {"scale": "Agoraphobia", "item_code": "hitop_161", "question_text": "Tive medo de ter um ataque de pânico num espaço pequeno, apertado ou fechado."},
    {"scale": "Antisocial Behavior", "item_code": "ext_154", "question_text": "Vandalizei ou destruí propriedade pública."},
    {"scale": "Antisocial Behavior", "item_code": "ext_227", "question_text": "Magoei animais e senti um certo prazer com isso."},
    {"scale": "Antisocial Behavior", "item_code": "ext_263", "question_text": "Tive problemas com a justiça ou com as autoridades policiais por não cumprir a lei."},
    {"scale": "Antisocial Behavior", "item_code": "ext_308", "question_text": "Falsifiquei cheques ou usei cartões de crédito de outras pessoas sem permissão."},
    {"scale": "Antisocial Behavior", "item_code": "ext_369", "question_text": "Tirei algo (por exemplo, dinheiro) de uma pessoa conhecida sem que ela soubesse."},
    {"scale": "Antisocial Behavior", "item_code": "ext_37", "question_text": "Tive relações sexuais de forma forçada ou sem o consentimento da outra pessoa."},
    {"scale": "Antisocial Behavior", "item_code": "ext_415", "question_text": "Invadi casas, edifícios ou carros."},
    {"scale": "Antisocial Behavior", "item_code": "ext_488", "question_text": "Ameacei ou intimidei alguém com um objeto perigoso (como uma pedra, um bastão, uma faca ou pistola)"},
    {"scale": "Appetite Loss", "item_code": "hitop_197", "question_text": "Tive pouco apetite."},
    {"scale": "Appetite Loss", "item_code": "hitop_198", "question_text": "Perdi muito peso sem sequer me esforçar para isso."},
    {"scale": "Appetite Loss", "item_code": "hitop_199", "question_text": "Não tive muita vontade de comer."},
    {"scale": "Binge Eating", "item_code": "hitop_87", "question_text": "Assim que começava a comer, não conseguia parar."},
    {"scale": "Binge Eating", "item_code": "hitop_92", "question_text": "Não consegui resistir a comer."},
    {"scale": "Binge Eating", "item_code": "hitop_93", "question_text": "Comi uma grande quantidade de comida num espaço curto de tempo (por exemplo, em 2 horas)."},
    {"scale": "Bodily Distress", "item_code": "hitop_449", "question_text": "Tive dores em várias partes do meu corpo."},
    {"scale": "Bodily Distress", "item_code": "hitop_450", "question_text": "Senti os meus músculos fracos."},
    {"scale": "Bodily Distress", "item_code": "hitop_451", "question_text": "Senti que algo estava errado com o meu corpo."},
    {"scale": "Bodily Distress", "item_code": "hitop_452", "question_text": "Tive sintomas gástricos que me incomodaram (diarreia, náusea, dores de estômago, etc.)."},
    {"scale": "Bodily Distress", "item_code": "hitop_455", "question_text": "Senti dores no peito."},
    {"scale": "Bodily Distress", "item_code": "hitop_456", "question_text": "Tive vários sintomas corporais que me incomodaram  (por exemplo, dores de cabeça, fadiga ou problemas de estômago) sem nenhuma explicação médica."},
    {"scale": "Body Dissatisfaction", "item_code": "hitop_105", "question_text": "Não consegui parar de comparar o meu corpo com o das outras pessoas."},
    {"scale": "Body Dissatisfaction", "item_code": "hitop_206", "question_text": "Desejei poder mudar certas partes do meu corpo."},
    {"scale": "Body Dissatisfaction", "item_code": "hitop_96", "question_text": "Senti insatisfação com a forma do meu corpo."},
    {"scale": "Body Dissatisfaction", "item_code": "hitop_99", "question_text": "Não gostei do meu peso (nomeadamente, o número na balança)."},
    {"scale": "Body Focus", "item_code": "hitop_208", "question_text": "Passei muito tempo a olhar para o meu próprio corpo."},
    {"scale": "Body Focus", "item_code": "hitop_210", "question_text": "Se passava por uma superfície refletora (como uma janela), verificava o meu aspeto."},
    {"scale": "Body Focus", "item_code": "hitop_211", "question_text": "Passei muito tempo a arranjar-me antes de sair."},
    {"scale": "Body Focus", "item_code": "hitop_212", "question_text": "Prestei muita atenção ao meu aspeto."},
    {"scale": "Body Focus", "item_code": "hitop_213", "question_text": "Passei muito tempo a arranjar-me."},
    {"scale": "Callousness", "item_code": "ext_103", "question_text": "Dei pouca importância ao que os outros precisavam."},
    {"scale": "Callousness", "item_code": "ext_127", "question_text": "Não me importei realmente com aquilo que os outros estavam a sentir."},
    {"scale": "Callousness", "item_code": "ext_212", "question_text": "As pessoas nem sempre me despertaram muita compaixão."},
    {"scale": "Callousness", "item_code": "ext_367", "question_text": "As pessoas disseram-me que fui frio(a)."},
    {"scale": "Callousness", "item_code": "ext_402", "question_text": "Nem sempre me preocupei em ajudar os outros."},
    {"scale": "Callousness", "item_code": "ext_5", "question_text": "Algumas pessoas acharam que fui indiferente e insensível."},
    {"scale": "Checking", "item_code": "hitop_214", "question_text": "Senti uma forte necessidade de verificar algo para ver se o tinha feito realmente."},
    {"scale": "Checking", "item_code": "hitop_215", "question_text": "Mesmo quando fui muito cuidadoso(a), preocupei-me se tinha feito as coisas corretamente."},
    {"scale": "Checking", "item_code": "hitop_216", "question_text": "Fiquei em dúvida constante sobre se teria falhado em fazer algo importante."},
    {"scale": "Checking", "item_code": "hitop_218", "question_text": "Depois de ter saído de casa, preocupei-me se me tinha esquecido de fazer alguma coisa."},
    {"scale": "Checking", "item_code": "hitop_219", "question_text": "Dei por mim a preocupar-me se tinha realmente feito algo ou se tinha apenas pensado em fazê-lo ."},
    {"scale": "Cleaning", "item_code": "hitop_221", "question_text": "Foi difícil para mim tocar em algo que estava sujo."},
    {"scale": "Cleaning", "item_code": "hitop_222", "question_text": "A ideia de poder apanhar germes ou bactérias através do contacto com animais preocupou-me."},
    {"scale": "Cleaning", "item_code": "hitop_223", "question_text": "Evitei contacto com pessoas porque me preocupava apanhar germes ou bactérias."},
    {"scale": "Cleaning", "item_code": "hitop_224", "question_text": "Senti necessidade de lavar as minhas mãos várias vezes."},
    {"scale": "Cleaning", "item_code": "hitop_226", "question_text": "Estive obcecado/a com a limpeza."},
    {"scale": "Cleaning", "item_code": "hitop_228", "question_text": "Tive de me lavar porque me sentia contaminado(a)."},
    {"scale": "Cognitive Problems", "item_code": "ext_300", "question_text": "Tive dificuldades em pensar de forma clara."},
    {"scale": "Cognitive Problems", "item_code": "ext_64", "question_text": "Senti a minha mente confusa."},
    {"scale": "Cognitive Problems", "item_code": "hitop_230", "question_text": "Distraí-me facilmente."},
    {"scale": "Cognitive Problems", "item_code": "hitop_231", "question_text": "Tive dificuldade em lembrar-me de coisas."},
    {"scale": "Cognitive Problems", "item_code": "hitop_543", "question_text": "Os meus pensamentos estavam sempre a saltar de uma coisa para outra."},
    {"scale": "Conversion Symptoms", "item_code": "hitop_458", "question_text": "Tive uma perda sensorial súbita (por exemplo, problemas de visão ou audição) sem explicação médica."},
    {"scale": "Conversion Symptoms", "item_code": "hitop_460", "question_text": "Aconteceu-me tocar em objetos e não os sentir (por exemplo, em relação à sua textura ou temperatura)."},
    {"scale": "Conversion Symptoms", "item_code": "hitop_461", "question_text": "Houve momentos em que deixei de ouvir, mesmo não tendo um problema auditivo diagnosticado."},
    {"scale": "Conversion Symptoms", "item_code": "hitop_462", "question_text": "Senti fraqueza muscular ou paralisias súbitas."},
    {"scale": "Conversion Symptoms", "item_code": "hitop_463", "question_text": "Houve momentos em que perdi o controlo do meu corpo (como num ataque ou convulsão), mesmo não tendo nenhum problema médico diagnosticado."},
    {"scale": "Conversion Symptoms", "item_code": "hitop_464", "question_text": "Houve momentos em que deixei de ver, mesmo não tendo um problema de visão diagnosticado."},
    {"scale": "Conversion Symptoms", "item_code": "hitop_467", "question_text": "Houve momentos em que perdi a consciência ou desmaiei, mesmo não tendo um problema médico diagnosticado."},
    {"scale": "Counting", "item_code": "hitop_233", "question_text": "Senti uma necessidade, compulsão ou impulso para contar coisas (por exemplo, números, objetos, passos, ...)."},
    {"scale": "Counting", "item_code": "hitop_234", "question_text": "Evitei usar números que parecem trazer azar."},
    {"scale": "Counting", "item_code": "hitop_235", "question_text": "Contei coisas (por exemplo, números, objetos, passos, ...) várias vezes."},
    {"scale": "Counting", "item_code": "hitop_237", "question_text": "Pensei que certos números me davam sorte."},
    {"scale": "Counting", "item_code": "hitop_238", "question_text": "Antes de iniciar uma atividade, precisei de contar até um determinado número."},
    {"scale": "Dietary Restraint", "item_code": "hitop_107", "question_text": "Tentei comer apenas alimentos saudáveis."},
    {"scale": "Dietary Restraint", "item_code": "hitop_109", "question_text": "Tentei limitar a quantidade de alimentos gordurosos que comi."},
    {"scale": "Dietary Restraint", "item_code": "hitop_110", "question_text": "Passei tempo a planear como reduzir a quantidade de comida que ingeri."},
    {"scale": "Dietary Restraint", "item_code": "hitop_111", "question_text": "Foquei-me em comer mais alimentos saudáveis."},
    {"scale": "Dietary Restraint", "item_code": "hitop_114", "question_text": "Tentei comer menos entre refeições (por exemplo, evitei petiscar, pequenos lanches ou snacks) ."},
    {"scale": "Difficulties Reaching Orgasm", "item_code": "hitop_397", "question_text": "Não consegui atingir o orgasmo."},
    {"scale": "Difficulties Reaching Orgasm", "item_code": "hitop_398", "question_text": "Atingi o orgasmo mais tarde do que queria."},
    {"scale": "Difficulties Reaching Orgasm", "item_code": "hitop_442", "question_text": "Tive dificuldades em atingir o orgasmo."},
    {"scale": "Disease Conviction", "item_code": "hitop_471", "question_text": "Tive uma doença que as outras pessoas desvalorizaram."},
    {"scale": "Disease Conviction", "item_code": "hitop_474", "question_text": "Fiquei zangado/a quando as pessoas não levaram a sério os meus problemas de saúde."},
    {"scale": "Disease Conviction", "item_code": "hitop_478", "question_text": "Foi difícil encontrar profissionais de saúde que reconhecessem a minha doença."},
    {"scale": "Disease Conviction", "item_code": "hitop_479", "question_text": "Fiquei frustrado/a por ter de convencer as pessoas de que tinha uma doença real."},
    {"scale": "Dishonesty - Deceitfulness", "item_code": "ext_303", "question_text": "Disse coisas que não eram verdade."},
    {"scale": "Dishonesty - Deceitfulness", "item_code": "ext_395", "question_text": "Estive disposto/a a dizer uma pequena mentira para tornar as coisas mais fáceis para mim."},
    {"scale": "Dishonesty - Deceitfulness", "item_code": "ext_432", "question_text": "Acreditei que não havia problema em contar uma pequena mentira para me livrar de problemas."},
    {"scale": "Dishonesty - Deceitfulness", "item_code": "ext_444", "question_text": "Menti sobre mim às outras pessoas."},
    {"scale": "Dishonesty - Manipulativeness", "item_code": "ext_101", "question_text": "Tentei enganar ou ludibriar outras pessoas."},
    {"scale": "Dishonesty - Manipulativeness", "item_code": "ext_22", "question_text": "Achei fácil enganar os outros."},
    {"scale": "Dishonesty - Manipulativeness", "item_code": "ext_262", "question_text": "Achei fácil manipular os outros."},
    {"scale": "Dishonesty - Manipulativeness", "item_code": "ext_38", "question_text": "Foi bastante fácil fazer as pessoas acreditarem em quase tudo o que eu queria."},
    {"scale": "Disorganization", "item_code": "ext_13", "question_text": "Nunca cheguei a horas."},
    {"scale": "Disorganization", "item_code": "ext_320", "question_text": "Tive dificuldades em fazer planos e cumprir horários."},
    {"scale": "Disorganization", "item_code": "ext_361", "question_text": "Atrasei-me a pagar contas ou falhei outros prazos importantes."},
    {"scale": "Disorganization", "item_code": "ext_374", "question_text": "Perdi coisas de que precisava."},
    {"scale": "Disorganization", "item_code": "ext_429", "question_text": "Podia ter melhorado as minhas capacidades de organização."},
    {"scale": "Disorganization", "item_code": "ext_442", "question_text": "Falhei compromissos porque me esqueci."},
    {"scale": "Disorganization", "item_code": "ext_97", "question_text": "Fui uma pessoa desarrumada."},
    {"scale": "Dissociation", "item_code": "hitop_469", "question_text": "Tive a sensação repentina de que tudo era desconhecido e esqueci-me de onde estava."},
    {"scale": "Dissociation", "item_code": "hitop_547", "question_text": "Senti-me como se já não existisse."},
    {"scale": "Dissociation", "item_code": "hitop_552", "question_text": "Tive apagões ou períodos em que perdi a noção do tempo."},
    {"scale": "Dissociation", "item_code": "hitop_554", "question_text": "Senti que as coisas à minha volta não eram reais."},
    {"scale": "Dissociation", "item_code": "hitop_557", "question_text": "Senti que estava fora do meu corpo."},
    {"scale": "Dissociation", "item_code": "hitop_558", "question_text": "Tive dificuldade em dizer se algo realmente aconteceu ou se só imaginei."},
    {"scale": "Distress - Dysphoria (Anhedonia)", "item_code": "hitop_173", "question_text": "Nada me pareceu interessante."},
    {"scale": "Distress - Dysphoria (Anhedonia)", "item_code": "hitop_508", "question_text": "A maior parte das coisas não me entusiasmava."},
    {"scale": "Distress - Dysphoria (Anhedonia)", "item_code": "hitop_8", "question_text": "Não senti a felicidade e o prazer que a maioria das pessoas sente."},
    {"scale": "Distress - Dysphoria (Anxious Worry)", "item_code": "hitop_187", "question_text": "Senti-me sufocado/a pela ansiedade."},
    {"scale": "Distress - Dysphoria (Anxious Worry)", "item_code": "hitop_190", "question_text": "Senti-me nervoso/a."},
    {"scale": "Distress - Dysphoria (Anxious Worry)", "item_code": "hitop_191", "question_text": "Senti-me muito stressado/a."},
    {"scale": "Distress - Dysphoria (Depressed Mood)", "item_code": "exp12", "question_text": "Senti-me sem esperança em relação ao futuro."},
    {"scale": "Distress - Dysphoria (Depressed Mood)", "item_code": "exp14", "question_text": "Senti-me inútil."},
    {"scale": "Distress - Dysphoria (Depressed Mood)", "item_code": "exp8", "question_text": "Senti-me deprimido/a."},
    {"scale": "Distress - Dysphoria (Depressed Mood)", "item_code": "exp9", "question_text": "Senti-me em baixo e desanimado/a."},
    {"scale": "Distress - Dysphoria (Lassitude)", "item_code": "exp17", "question_text": "Foi necessário muito esforço para querer continuar."},
    {"scale": "Distress - Dysphoria (Lassitude)", "item_code": "exp18", "question_text": "Tive muito pouca energia."},
    {"scale": "Distress - Dysphoria (Lassitude)", "item_code": "exp19", "question_text": "Senti-me exausto/a"},
    {"scale": "Distress - Dysphoria (Shame/Guilt)", "item_code": "hitop_333", "question_text": "Fiquei enojado/a de mim próprio/a."},
    {"scale": "Distress - Dysphoria (Shame/Guilt)", "item_code": "hitop_334", "question_text": "Culpei-me pelas coisas."},
    {"scale": "Distress - Dysphoria (Shame/Guilt)", "item_code": "hitop_336", "question_text": "Tive vergonha de mim próprio/a."},
    {"scale": "Domineering", "item_code": "ext_50", "question_text": "Gostei de ter poder."},
    {"scale": "Domineering", "item_code": "hitop_17", "question_text": "Foi muito importante para mim assumir a liderança."},
    {"scale": "Domineering", "item_code": "hitop_18", "question_text": "Gostei de ser a pessoa que tinha a autoridade."},
    {"scale": "Domineering", "item_code": "hitop_19", "question_text": "Quando estava em grupo, gostei de estar ao comando e a liderar."},
    {"scale": "Domineering", "item_code": "hitop_21", "question_text": "As coisas correram melhor quando eu disse às outras pessoas o que fazer."},
    {"scale": "Domineering", "item_code": "hitop_23", "question_text": "Fui a pessoa superior ou dominante nas minhas relações com os outros."},
    {"scale": "Eccentricity", "item_code": "hitop_560", "question_text": "Várias pessoas acharam que o meu comportamento era muito estranho."},
    {"scale": "Eccentricity", "item_code": "hitop_562", "question_text": "Pensei sobre as coisas de forma invulgar ou estranha."},
    {"scale": "Eccentricity", "item_code": "hitop_564", "question_text": "Disse coisas fora do comum."},
    {"scale": "Eccentricity", "item_code": "hitop_566", "question_text": "As pessoas disseram que eu era estranho/a."},
    {"scale": "Eccentricity", "item_code": "hitop_567", "question_text": "Os outros disseram que o meu comportamento não era o mais correto."},
    {"scale": "Emotionality (Affective Lability)", "item_code": "hitop_570", "question_text": "O meu humor foi intenso e imprevisível."},
    {"scale": "Emotionality (Affective Lability)", "item_code": "hitop_571", "question_text": "O meu estado de humor mudou de repente sem razão aparente."},
    {"scale": "Emotionality (Affective Lability)", "item_code": "hitop_572", "question_text": "Passei rapidamente de estar triste para estar feliz."},
    {"scale": "Emotionality (Angry Hostility)", "item_code": "ext_193", "question_text": "Zanguei-me por coisas pequenas."},
    {"scale": "Emotionality (Angry Hostility)", "item_code": "ext_323", "question_text": "Fiquei tão zangado/a que gritei ou berrei."},
    {"scale": "Emotionality (Angry Hostility)", "item_code": "ext_514", "question_text": "Tive explosões de raiva."},
    {"scale": "Emotionality (Angry Hostility)", "item_code": "ext_89", "question_text": "O meu feitio assustou as pessoas."},
    {"scale": "Emotionality (Irritability)", "item_code": "exp4", "question_text": "Irritei-me facilmente."},
    {"scale": "Emotionality (Irritability)", "item_code": "exp5", "question_text": "Estive rabugento/a."},
    {"scale": "Emotionality (Irritability)", "item_code": "exp6", "question_text": "Estive muito irritadiço/a."},
    {"scale": "Emotionality (Irritability)", "item_code": "exp7", "question_text": "Pequenas frustrações chatearam-me muito."},
    {"scale": "Entitlement", "item_code": "ext_136", "question_text": "Fui egoísta."},
    {"scale": "Entitlement", "item_code": "ext_175", "question_text": "Devido ao meu valor, senti que merecia ser tratado/a de forma especial."},
    {"scale": "Entitlement", "item_code": "ext_216", "question_text": "Pus as minhas necessidades e desejos em primeiro lugar."},
    {"scale": "Entitlement", "item_code": "ext_255", "question_text": "Algumas pessoas acharam que fui egocêntrico/a."},
    {"scale": "Entitlement", "item_code": "ext_370", "question_text": "Devido ao meu valor, esperei que me tratassem melhor do que às outras pessoas."},
    {"scale": "Entitlement", "item_code": "ext_381", "question_text": "Senti inveja do que os outros tinham."},
    {"scale": "Excessive Exercise", "item_code": "hitop_115", "question_text": "As pessoas disseram-me que estava a fazer demasiado exercício físico."},
    {"scale": "Excessive Exercise", "item_code": "hitop_116", "question_text": "Fiz mais exercício físico do que seria bom para mim."},
    {"scale": "Excessive Exercise", "item_code": "hitop_120", "question_text": "Fiz exercício físico até me sentir mal."},
    {"scale": "Excessive Exercise", "item_code": "hitop_121", "question_text": "Fiz exercício físico quando estive lesionado/a ou com dores."},
    {"scale": "Excessive Exercise", "item_code": "hitop_123", "question_text": "Alterei ou cancelei planos para ter mais tempo para treinar e fazer exercício físico."},
    {"scale": "Excoriation", "item_code": "hitop_246", "question_text": "Causei lesões na minha própria pele (ao arranhar ou arrancar pele) que me causaram problemas."},
    {"scale": "Excoriation", "item_code": "hitop_247", "question_text": "Tentei esconder zonas do corpo onde tinha arrancado/arranhado a minha própria pele."},
    {"scale": "Excoriation", "item_code": "hitop_248", "question_text": "Arranquei/arranhei áreas da minha pele de que não gosto."},
    {"scale": "Exhibitionism", "item_code": "hitop_11", "question_text": "Gostei de atrair a atenção das outras pessoas."},
    {"scale": "Exhibitionism", "item_code": "hitop_16", "question_text": "Gostei de ser o centro das atenções."},
    {"scale": "Exhibitionism", "item_code": "hitop_577", "question_text": "Fiz coisas para que os outros reparassem em mim."},
    {"scale": "Exhibitionism", "item_code": "hitop_581", "question_text": "Vesti roupas que chamassem a atenção."},
    {"scale": "Exhibitionism", "item_code": "hitop_9", "question_text": "Quando estive em público, gostei de me evidenciar."},
    {"scale": "Fantasy Proneness", "item_code": "hitop_582", "question_text": "Tive a tendência para sonhar acordado/a."},
    {"scale": "Fantasy Proneness", "item_code": "hitop_583", "question_text": "Em alguns momentos, senti que as minhas fantasias estavam mesmo a acontecer."},
    {"scale": "Fantasy Proneness", "item_code": "hitop_584", "question_text": "Desejei viver nas minhas fantasias, em vez de na vida real."},
    {"scale": "Fantasy Proneness", "item_code": "hitop_585", "question_text": "A minha mente divagou para longe do presente."},
    {"scale": "Fantasy Proneness", "item_code": "hitop_586", "question_text": "Passei horas na minha própria imaginação."},
    {"scale": "Fantasy Proneness", "item_code": "hitop_588", "question_text": "Perdi-me ao imaginar-me numa personagem fictícia."},
    {"scale": "Food Selectivity", "item_code": "hitop_77", "question_text": "As pessoas disseram-me que eu fui muito esquisito/a a comer."},
    {"scale": "Food Selectivity", "item_code": "hitop_78", "question_text": "Evitei alimentos por causa do seu cheiro ou textura."},
    {"scale": "Food Selectivity", "item_code": "hitop_81", "question_text": "Evitei alimentos por não gostar do seu aspeto."},
    {"scale": "Food Selectivity", "item_code": "hitop_85", "question_text": "Muitos tipos de comida fizeram-me sentir enojado/a."},
    {"scale": "Gambling", "item_code": "ext_20", "question_text": "Fui incapaz de resistir ao impulso de fazer apostas."},
    {"scale": "Gambling", "item_code": "ext_210", "question_text": "Foi-me difícil parar de fazer apostas após ter começado."},
    {"scale": "Gambling", "item_code": "ext_26", "question_text": "Continuei a fazer apostas (jogos online, raspadinhas, euromilhões ou casino), apesar disso causar problemas nas minhas relações pessoais."},
    {"scale": "Gambling", "item_code": "ext_261", "question_text": "Apostei mais dinheiro do que aquele que podia perder."},
    {"scale": "Gambling", "item_code": "ext_269", "question_text": "Fiquei com dívidas ou a dever dinheiro por causa de apostas"},
    {"scale": "Gaming", "item_code": "ext_135", "question_text": "Continuei a jogar, apesar disso me ter causado problemas no trabalho ou na escola."},
    {"scale": "Gaming", "item_code": "ext_350", "question_text": "Recusei convites para socializar para passar mais tempo a jogar."},
    {"scale": "Gaming", "item_code": "ext_45", "question_text": "Procurei formas para ter mais tempo para jogar."},
    {"scale": "Gaming", "item_code": "ext_65", "question_text": "O meu humor piorou quando não pude jogar o tempo que queria."},
    {"scale": "Grandiosity", "item_code": "ext_219", "question_text": "As pessoas admiraram-me."},
    {"scale": "Grandiosity", "item_code": "ext_380", "question_text": "Reconheci que tinha muitas qualidades especiais."},
    {"scale": "Grandiosity", "item_code": "ext_41", "question_text": "Gostei de pensar sobre o meu futuro e as coisas boas que ele traria."},
    {"scale": "Catch", "item_code": "catch_1", "question_text": "Para confirmar que está atento(a) ao questionário, indique \"Nada\"."},
    {"scale": "Catch", "item_code": "catch_2", "question_text": "O planeta Marte é azul. Por favor, selecione a resposta  \"Muito\"."},
    {"scale": "Catch", "item_code": "catch_3", "question_text": "Por favor selecione \"Moderadamente\" para indicar que está a responder com atenção."},
    {"scale": "Grandiosity", "item_code": "ext_43", "question_text": "Gostei de me olhar ao espelho."},
    {"scale": "Grandiosity", "item_code": "ext_441", "question_text": "A maioria das pessoas gostaria de ser como eu sou."},
    {"scale": "Grandiosity", "item_code": "ext_498", "question_text": "Estive muito confiante de mim ao pé de outras pessoas."},
    {"scale": "Health Anxiety", "item_code": "hitop_483", "question_text": "Passei demasiado tempo a pensar sobre doenças que poderia ter."},
    {"scale": "Health Anxiety", "item_code": "hitop_487", "question_text": "Ler artigos sobre doenças fez-me preocupar com a minha saúde."},
    {"scale": "Health Anxiety", "item_code": "hitop_488", "question_text": "Preocupei-me muito com a minha saúde."},
    {"scale": "Health Anxiety", "item_code": "hitop_490", "question_text": "Tive medo de ter uma doença grave."},
    {"scale": "Hoarding", "item_code": "exp24", "question_text": "Tive dificuldade em deitar coisas ao lixo."},
    {"scale": "Hoarding", "item_code": "exp25", "question_text": "Colecionei coisas de que não precisava."},
    {"scale": "Hoarding", "item_code": "hitop_256", "question_text": "A minha casa estava tão cheia de coisas que se tornava difícil andar de um lado para o outro."},
    {"scale": "Hoarding", "item_code": "hitop_258", "question_text": "Mesmo quando não preciso, não resisto a comprar coisas"},
    {"scale": "Hoarding", "item_code": "hitop_259", "question_text": "As minhas compras por impulso já me causaram problemas ou deixaram-me preocupado com questões financeiras."},
    {"scale": "Hoarding", "item_code": "hitop_261", "question_text": "Guardei objetos de que não precisava."},
    {"scale": "Hyperdeliberation", "item_code": "ext_145", "question_text": "Pensei muito sobre as minhas ideias antes de agir."},
    {"scale": "Hyperdeliberation", "item_code": "ext_189", "question_text": "Examinei todas as opções possíveis antes de escolher algo."},
    {"scale": "Hyperdeliberation", "item_code": "ext_291", "question_text": "Antes de tomar uma decisão importante, precisei de meses de reflexão profunda para chegar a uma conclusão."},
    {"scale": "Hyperdeliberation", "item_code": "ext_35", "question_text": "Só tomei decisões depois de ter toda a informação que era possível obter."},
    {"scale": "Hyperdeliberation", "item_code": "ext_438", "question_text": "Ponderei cuidadosamente os prós e os contras antes de tomar qualquer decisão."},
    {"scale": "Hyperdeliberation", "item_code": "ext_457", "question_text": "Passei tempo a considerar todos os resultados possíveis antes de tomar alguma decisão."},
    {"scale": "Hypervigilance", "item_code": "hitop_367", "question_text": "Senti-me como se estivesse em perigo."},
    {"scale": "Hypervigilance", "item_code": "hitop_368", "question_text": "Senti-me alerta e no meu limite de tensão."},
    {"scale": "Hypervigilance", "item_code": "hitop_369", "question_text": "Assustei-me facilmente."},
    {"scale": "Hypervigilance", "item_code": "hitop_371", "question_text": "Senti que o mundo era um lugar perigoso."},
    {"scale": "Hypervigilance", "item_code": "hitop_372", "question_text": "Estive atento/a a possíveis ameaças ou sinais de perigo à minha volta."},
    {"scale": "Hypervigilance", "item_code": "hitop_54", "question_text": "Preocupei-me que outras pessoas me pudessem fazer mal."},
    {"scale": "Insomnia", "item_code": "hitop_270", "question_text": "Dormi muito mal."},
    {"scale": "Insomnia", "item_code": "hitop_271", "question_text": "Tive problemas em manter-me a dormir."},
    {"scale": "Insomnia", "item_code": "hitop_273", "question_text": "Acordei cedo e não consegui voltar a dormir."},
    {"scale": "Insomnia", "item_code": "hitop_274", "question_text": "Tive dificuldades em adormecer."},
    {"scale": "Low Sexual Arousal", "item_code": "hitop_403", "question_text": "Foi-me difícil ficar sexualmente excitado/a."},
    {"scale": "Low Sexual Arousal", "item_code": "hitop_404", "question_text": "Foi-me difícil manter a excitação sexual após iniciar uma atividade sexual."},
    {"scale": "Low Sexual Arousal", "item_code": "hitop_406", "question_text": "Não senti excitação sexual suficiente (ereção do pénis ou lubrificação vaginal) para desfrutar do sexo."},
    {"scale": "Low Sexual Interest", "item_code": "hitop_399", "question_text": "Tive pouco ou nenhum interesse em atividades sexuais."},
    {"scale": "Low Sexual Interest", "item_code": "hitop_400", "question_text": "Senti pouco desejo por atividades sexuais."},
    {"scale": "Low Sexual Interest", "item_code": "hitop_432", "question_text": "Senti-me desinteressado/a durante a atividade sexual."},
    {"scale": "Manic Energy", "item_code": "hitop_239", "question_text": "As outras pessoas notaram que eu estava com mais energia do que o normal."},
    {"scale": "Manic Energy", "item_code": "hitop_241", "question_text": "Senti-me muito mais energético/a ou hiperativo/a do que o habitual."},
    {"scale": "Manic Energy", "item_code": "hitop_243", "question_text": "Estive bastante mais falador/a do que o habitual."},
    {"scale": "Manic Energy", "item_code": "hitop_244", "question_text": "Tive tanta energia que as outras pessoas não me conseguiam acompanhar."},
    {"scale": "Manic Energy", "item_code": "hitop_262", "question_text": "Tive tanta energia que senti que podia estar vários dias sem precisar de dormir."},
    {"scale": "Manic Energy", "item_code": "hitop_265", "question_text": "Senti que conseguia estar sempre a fazer alguma coisa, sem me cansar."},
    {"scale": "Manic Energy", "item_code": "hitop_645", "question_text": "Tive muita mais energia do que o normal."},
    {"scale": "Mistrust (Cynicism)", "item_code": "ext_198", "question_text": "Senti que as pessoas foram essencialmente egoístas, com pouca consideração pelos outros."},
    {"scale": "Mistrust (Cynicism)", "item_code": "ext_279", "question_text": "Senti que as outras pessoas não eram de confiar."},
    {"scale": "Mistrust (Cynicism)", "item_code": "ext_448", "question_text": "Acreditei que se não tivesse cuidado, as outras pessoas iriam aproveitar-se de mim."},
    {"scale": "Mistrust (Cynicism)", "item_code": "ext_79", "question_text": "Senti que a maioria das pessoas só querem saber de si próprias."},
    {"scale": "Mistrust (Suspiciousness)", "item_code": "ext_58", "question_text": "Algumas pessoas quiseram magoar-me."},
    {"scale": "Mistrust (Suspiciousness)", "item_code": "hitop_56", "question_text": "As pessoas falaram nas minhas costas."},
    {"scale": "Mistrust (Suspiciousness)", "item_code": "hitop_661", "question_text": "Fiquei muito desconfiado/a de outras pessoas."},
    {"scale": "Mistrust (Suspiciousness)", "item_code": "hitop_662", "question_text": "Senti que outras pessoas estavam a agir contra mim."},
    {"scale": "Muscle Building", "item_code": "hitop_128", "question_text": "Foi importante para mim ganhar massa muscular e eliminar gordura corporal."},
    {"scale": "Muscle Building", "item_code": "hitop_129", "question_text": "O meu objetivo principal para estar em boa forma passou por aumentar a massa muscular e, ao mesmo tempo,  manter-me magro/a."},
    {"scale": "Muscle Building", "item_code": "hitop_131", "question_text": "Quis ter abdominais bem definidos."},
    {"scale": "Muscle Building", "item_code": "hitop_132", "question_text": "Ser musculado/a foi muito importante para mim."},
    {"scale": "Muscle Building", "item_code": "hitop_133", "question_text": "Usei medicamentos ou suplementos para ficar mais musculado/a."},
    {"scale": "Nightmares", "item_code": "hitop_275", "question_text": "Tive pesadelos que me fizeram acordar durante a noite."},
    {"scale": "Nightmares", "item_code": "hitop_278", "question_text": "Tive um pesadelo recorrente."},
    {"scale": "Nightmares", "item_code": "hitop_279", "question_text": "Tive um sonho tão perturbador que continuou a afetar-me mesmo depois de acordar."},
    {"scale": "Non-persistence", "item_code": "ext_11", "question_text": "Desisti de tarefas (emprego, trabalhos de casa ou tarefas domésticas) antes de ter terminado."},
    {"scale": "Non-persistence", "item_code": "ext_197", "question_text": "Não consegui retomar uma tarefa depois de me ter distraído."},
    {"scale": "Non-persistence", "item_code": "ext_256", "question_text": "Desisti de tarefas que se tornaram demasiado desafiantes ou exigentes."},
    {"scale": "Non-persistence", "item_code": "ext_257", "question_text": "Fui incapaz de me concentrar numa tarefa quando ela não me interessava."},
    {"scale": "Non-persistence", "item_code": "ext_297", "question_text": "Perdi facilmente o interesse em tarefas que comecei a fazer."},
    {"scale": "Non-planfulness", "item_code": "ext_102", "question_text": "Tomei decisões de forma rápida, sem pensar bem nelas."},
    {"scale": "Non-planfulness", "item_code": "ext_166", "question_text": "Disse coisas sem pensar."},
    {"scale": "Non-planfulness", "item_code": "ext_264", "question_text": "Agi por impulso."},
    {"scale": "Non-planfulness", "item_code": "ext_476", "question_text": "Fiz algo espontâneo de que me arrependi mais tarde."},
    {"scale": "Non-planfulness", "item_code": "ext_56", "question_text": "Falhei em antecipar as consequências das minhas ações."},
    {"scale": "NSSI", "item_code": "ext_152", "question_text": "Mordi-me de propósito."},
    {"scale": "NSSI", "item_code": "ext_266", "question_text": "Magoei-me de propósito."},
    {"scale": "NSSI", "item_code": "ext_468", "question_text": "Senti vontade de me magoar (cortar, queimar, morder, etc)."},
    {"scale": "NSSI", "item_code": "hitop_281", "question_text": "Cortei-me de propósito."},
    {"scale": "NSSI", "item_code": "hitop_282", "question_text": "Por vezes, só queria sentir dor."},
    {"scale": "NSSI", "item_code": "hitop_286", "question_text": "Arranhei de propósito a minha pele com tanta força que começou a sangrar."},
    {"scale": "Oppositionality", "item_code": "ext_121", "question_text": "Gostei de me revoltar contra figuras de autoridade (por exemplo, polícia, professores, chefes)."},
    {"scale": "Oppositionality", "item_code": "ext_230", "question_text": "A vida pareceu-me demasiado curta para seguir as regras dos outros."},
    {"scale": "Oppositionality", "item_code": "ext_280", "question_text": "Transgredi ou quebrei as regras."},
    {"scale": "Oppositionality", "item_code": "ext_310", "question_text": "Agi sem me preocupar se o meu comportamento era considerado adequado ou não."},
    {"scale": "Oppositionality", "item_code": "ext_396", "question_text": "Ignorei, em grande medida, as regras da sociedade sobre como me devo comportar."},
    {"scale": "Oppositionality", "item_code": "ext_512", "question_text": "Fiz, de propósito, coisas que iam contra as regras."},
    {"scale": "Panic", "item_code": "hitop_288", "question_text": "Senti-me zonzo/a ou com tonturas."},
    {"scale": "Panic", "item_code": "hitop_289", "question_text": "Tive tremores."},
    {"scale": "Panic", "item_code": "hitop_290", "question_text": "O meu coração esteve acelerado ou a bater com muita força."},
    {"scale": "Panic", "item_code": "hitop_295", "question_text": "Tive medo de poder estar a ter um ataque cardíaco."},
    {"scale": "Panic", "item_code": "hitop_299", "question_text": "Senti-me tão mal que pensei que poderia morrer."},
    {"scale": "Paraphilias", "item_code": "ext_205", "question_text": "Os meus fetiches ou fantasias sexuais causaram problemas em algumas das minhas relações."},
    {"scale": "Paraphilias", "item_code": "hitop_407", "question_text": "Achei sexualmente excitante observar outras pessoas em momentos íntimos (por exemplo: nuas, a masturbarem-se ou a fazer sexo), sem que elas se apercebessem."},
    {"scale": "Paraphilias", "item_code": "hitop_408", "question_text": "A ideia de mostrar as minhas partes íntimas a pessoas desconhecidas causou-me alguma excitação."},
    {"scale": "Paraphilias", "item_code": "hitop_409", "question_text": "A ideia de tocar ou roçar-me em desconhecidos pareceu-me sexualmente excitante."},
    {"scale": "Paraphilias", "item_code": "hitop_410", "question_text": "A ideia de ter relações sexuais com alguém inconsciente (por exemplo, alguém a dormir ou sob efeito de substâncias) pareceu-me sexualmente excitante."},
    {"scale": "Perfectionism", "item_code": "ext_104", "question_text": "As pessoas disseram-me que estava a ser demasiado perfecionista."},
    {"scale": "Perfectionism", "item_code": "ext_500", "question_text": "O meu desejo de que as coisas ficassem perfeitas impediu-me de as acabar."},
    {"scale": "Perfectionism", "item_code": "hitop_300", "question_text": "Esforcei-me para atingir a perfeição, mesmo quando os outros me disseram que devia avançar."},
    {"scale": "Perfectionism", "item_code": "hitop_301", "question_text": "Senti que o meu trabalho tinha de estar perfeito."},
    {"scale": "Perfectionism", "item_code": "hitop_302", "question_text": "Exigi perfeição a mim próprio/a."},
    {"scale": "Premature Orgasm", "item_code": "exp22", "question_text": "Durante o sexo, normalmente atingi o ponto máximo de excitação (o \"clímax\") muito rápido."},
    {"scale": "Premature Orgasm", "item_code": "exp23", "question_text": "Durante o sexo, tentei intencionalmente atrasar o orgasmo para poder aguentar mais tempo."},
    {"scale": "Premature Orgasm", "item_code": "hitop_414", "question_text": "Atingi o orgasmo mais cedo do que queria."},
    {"scale": "Premature Orgasm", "item_code": "hitop_415", "question_text": "Fui incapaz de controlar o momento em que atingi o orgasmo."},
    {"scale": "Problematic Shopping", "item_code": "ext_238", "question_text": "Tive dificuldades em resistir à vontade de fazer compras."},
    {"scale": "Problematic Shopping", "item_code": "ext_281", "question_text": "Comprei muito mais do que precisava."},
    {"scale": "Problematic Shopping", "item_code": "ext_384", "question_text": "Mantive as minhas compras em segredo."},
    {"scale": "Problematic Shopping", "item_code": "ext_407", "question_text": "Gastei mais dinheiro em compras do que podia pagar."},
    {"scale": "Purging", "item_code": "hitop_153", "question_text": "Provoquei o vómito para não engordar."},
    {"scale": "Purging", "item_code": "hitop_154", "question_text": "Usei certos medicamentos (ex.: laxantes e diuréticos) para perder peso."},
    {"scale": "Purging", "item_code": "hitop_155", "question_text": "Considerei utilizar xaropes para induzir o vómito, laxantes, clísters ou supositórios para perder peso."},
    {"scale": "Reality Distortion (Delusions)", "item_code": "hitop_527", "question_text": "Senti que conseguia controlar objetos, pessoas ou situações através da minha mente."},
    {"scale": "Reality Distortion (Delusions)", "item_code": "hitop_531", "question_text": "Pensei que era possível que outras pessoas lessem a minha mente ou que eu lesse as delas."},
    {"scale": "Reality Distortion (Delusions)", "item_code": "hitop_532", "question_text": "Acreditei que outras pessoas podiam, de facto, ouvir os meus pensamentos."},
    {"scale": "Reality Distortion (Delusions)", "item_code": "hitop_533", "question_text": "Reparei que algumas mensagens eram enviadas especialmente para mim através de jornais, TV, cartazes, letras de música, etc."},
    {"scale": "Reality Distortion (Delusions)", "item_code": "hitop_534", "question_text": "Pensei, em alguns momentos, ter sido escolhido por Deus (ou outra entidade divina) para cumprir uma missão especial."},
    {"scale": "Reality Distortion (Hallucinations)", "item_code": "hitop_594", "question_text": "Experienciei visões ou sons estranhos."},
    {"scale": "Catch", "item_code": "catch_4", "question_text": "Os seres humanos têm quatro olhos. Por favor, selecione \"Moderadamente\"."},
    {"scale": "Catch", "item_code": "catch_5", "question_text": "Para fins de controlo de qualidade, escolha a opção \"Um pouco\"."},
    {"scale": "Reality Distortion (Hallucinations)", "item_code": "hitop_595", "question_text": "Em alguns momentos, senti cheiros que mais ninguém sentiu."},
    {"scale": "Reality Distortion (Hallucinations)", "item_code": "hitop_596", "question_text": "Vi coisas que não estavam realmente presentes."},
    {"scale": "Reality Distortion (Hallucinations)", "item_code": "hitop_601", "question_text": "Vi uma pessoa, mas depois percebi que era só uma sombra."},
    {"scale": "Reality Distortion (Hallucinations)", "item_code": "hitop_606", "question_text": "Em alguns momentos, ouvi sons que mais ninguém conseguiu ouvir."},
    {"scale": "Reality Distortion (Hallucinations)", "item_code": "hitop_608", "question_text": "Em alguns momentos, tive a impressão de que algo se mexia debaixo da minha pele."},
    {"scale": "Restlessness", "item_code": "ext_229", "question_text": "Senti-me irrequieto/a quando tive de permanecer parado por mais de 10 minutos."},
    {"scale": "Restlessness", "item_code": "ext_352", "question_text": "Tive dificuldades em permanecer no meu lugar quando era suposto estar sentado/a."},
    {"scale": "Restlessness", "item_code": "ext_418", "question_text": "Senti a necessidade de me levantar quando deveria estar sentado/a."},
    {"scale": "Restlessness", "item_code": "ext_460", "question_text": "Evitei atividades em que tivesse de ficar muito tempo parado/a ou sentado/a."},
    {"scale": "Restlessness", "item_code": "hitop_310", "question_text": "Tive dificuldades em permanecer parado/a."},
    {"scale": "Restricted Affectivity", "item_code": "ext_403", "question_text": "Escondi as minhas emoções."},
    {"scale": "Restricted Affectivity", "item_code": "hitop_29", "question_text": "Dificilmente mostrei sentimentos."},
    {"scale": "Restricted Affectivity", "item_code": "hitop_31", "question_text": "Não reagi a coisas que as outras pessoas acharam emotivas."},
    {"scale": "Restricted Affectivity", "item_code": "hitop_610", "question_text": "As pessoas disseram-me que não demonstro emoções."},
    {"scale": "Restricted Affectivity", "item_code": "hitop_618", "question_text": "Não expressei as minhas emoções."},
    {"scale": "Restricted Eating", "item_code": "hitop_147", "question_text": "As pessoas disseram-me que não comia o suficiente."},
    {"scale": "Restricted Eating", "item_code": "hitop_148", "question_text": "Saltei duas refeições seguidas."},
    {"scale": "Restricted Eating", "item_code": "hitop_150", "question_text": "Passei bastante tempo sem comer."},
    {"scale": "Restricted Eating", "item_code": "hitop_151", "question_text": "Arranjei desculpas para evitar comer."},
    {"scale": "Rigidity", "item_code": "ext_73", "question_text": "Por uma questão de princípio recusei-me a ceder ou a dar o braço a torcer, mesmo em assuntos sem importância."},
    {"scale": "Rigidity", "item_code": "hitop_305", "question_text": "Continuei a fazer as coisas da mesma maneira, mesmo quando isso claramente não funcionava."},
    {"scale": "Rigidity", "item_code": "hitop_306", "question_text": "Tive a certeza de que a minha maneira de fazer as coisas era a mais correta."},
    {"scale": "Rigidity", "item_code": "hitop_307", "question_text": "Não dei o braço a torcer porque sabia que estava certo/a."},
    {"scale": "Rigidity", "item_code": "hitop_309", "question_text": "Fui rígido/a e inflexível na minha forma de fazer coisas."},
    {"scale": "Risk Aversion", "item_code": "ext_165", "question_text": "Fiz de tudo para evitar riscos."},
    {"scale": "Risk Aversion", "item_code": "ext_515", "question_text": "Fui cauteloso/a."},
    {"scale": "Risk Aversion", "item_code": "hitop_34", "question_text": "Preferi fazer coisas da forma mais segura possível."},
    {"scale": "Risk Aversion", "item_code": "hitop_35", "question_text": "Fiquei desconfortável quando tive de arriscar."},
    {"scale": "Risk Aversion", "item_code": "hitop_37", "question_text": "Fui muito cauteloso/a relativamente a correr riscos."},
    {"scale": "Risk Aversion", "item_code": "hitop_39", "question_text": "Evitei correr riscos a todo o custo."},
    {"scale": "Risk Taking", "item_code": "ext_425", "question_text": "Procurei emoções fortes ."},
    {"scale": "Risk Taking", "item_code": "ext_495", "question_text": "As pessoas descrever-me-iam como uma pessoa que corre riscos."},
    {"scale": "Risk Taking", "item_code": "hitop_62", "question_text": "Desfrutei de atividades que eram um pouco perigosas."},
    {"scale": "Risk Taking", "item_code": "hitop_63", "question_text": "Correr riscos fez-me sentir vivo(a)."},
    {"scale": "Risky Sex", "item_code": "ext_114", "question_text": "Envolvi-me em algumas atividades sexuais das quais me arrependi mais tarde."},
    {"scale": "Risky Sex", "item_code": "ext_172", "question_text": "Envolvi-me em relações sexuais desprotegidas."},
    {"scale": "Risky Sex", "item_code": "ext_70", "question_text": "Usei o sexo como uma forma de aliviar ou escapar a sentimentos negativos (ex: frustração, ansiedade, tristeza, revolta)."},
    {"scale": "Risky Sex", "item_code": "hitop_322", "question_text": "Tive atividades sexuais arriscadas."},
    {"scale": "Romantic Disinterest", "item_code": "hitop_42", "question_text": "Senti que as relações românticas eram cansativas."},
    {"scale": "Romantic Disinterest", "item_code": "hitop_44", "question_text": "Senti que as relações românticas eram demasiado aborrecidas para mim."},
    {"scale": "Romantic Disinterest", "item_code": "hitop_624", "question_text": "Senti que não queria estar numa relação próxima."},
    {"scale": "Romantic Disinterest", "item_code": "hitop_625", "question_text": "Não tive interesse em relacionamentos românticos."},
    {"scale": "Romantic Disinterest", "item_code": "hitop_634", "question_text": "Senti-me menos feliz quando estive numa relação romântica."},
    {"scale": "Sex-Related Substance Use", "item_code": "hitop_419", "question_text": "Desfrutava ainda mais de atividades sexuais quando estava sob o efeito de drogas."},
    {"scale": "Sex-Related Substance Use", "item_code": "hitop_424", "question_text": "Usei substâncias para reduzir a ansiedade durante a atividade sexual."},
    {"scale": "Sex-Related Substance Use", "item_code": "hitop_426", "question_text": "Usei substâncias para achar o meu parceiro/a minha parceira mais atraente."},
    {"scale": "Sex-Related Substance Use", "item_code": "hitop_427", "question_text": "Usei substâncias durante o sexo e incentivei o meu parceiro/a a usar também."},
    {"scale": "Sexual Distress", "item_code": "hitop_428", "question_text": "Senti culpa por ter dificuldades sexuais."},
    {"scale": "Sexual Distress", "item_code": "hitop_429", "question_text": "Preocupei-me com a minha vida sexual."},
    {"scale": "Sexual Distress", "item_code": "hitop_430", "question_text": "Senti-me sexualmente desadequado/a."},
    {"scale": "Sexual Distress", "item_code": "hitop_431", "question_text": "Senti-me infeliz com o meu desempenho sexual."},
    {"scale": "Sexual Pain", "item_code": "hitop_433", "question_text": "Fiquei tenso/a durante atividades sexuais por sentir dor."},
    {"scale": "Sexual Pain", "item_code": "hitop_444", "question_text": "Achei o sexo fisicamente desconfortável."},
    {"scale": "Sexual Pain", "item_code": "hitop_445", "question_text": "Foi doloroso para mim ter (ou tentar ter) sexo com penetração vaginal ou anal."},
    {"scale": "Social Aggression", "item_code": "ext_171", "question_text": "Gozei com pessoas."},
    {"scale": "Social Aggression", "item_code": "ext_173", "question_text": "Tentei acabar com a amizade ou com a relação romântica de outra pessoa."},
    {"scale": "Social Aggression", "item_code": "ext_400", "question_text": "Insultei outras pessoas."},
    {"scale": "Social Aggression", "item_code": "ext_420", "question_text": "Disseram-me que conseguia ser um bully (ou seja, uma pessoa que faz bullying)."},
    {"scale": "Social Aggression", "item_code": "ext_67", "question_text": "Contei ou espalhei boatos/rumores sobre outras pessoas."},
    {"scale": "Social Aggression", "item_code": "ext_74", "question_text": "Ridicularizei outras pessoas."},
    {"scale": "Social Aloofness", "item_code": "hitop_50", "question_text": "Quando tive a oportunidade optei por estar sozinho/a, em vez de estar com outras pessoas."},
    {"scale": "Social Aloofness", "item_code": "hitop_626", "question_text": "Interagir ou conviver com os outros não teve grande importância para mim."},
    {"scale": "Social Aloofness", "item_code": "hitop_649", "question_text": "Não me apeteceu passar tempo com pessoas."},
    {"scale": "Social Aloofness", "item_code": "hitop_657", "question_text": "Senti-me mais feliz nos momentos em que estive sozinho/a."},
    {"scale": "Social Aloofness", "item_code": "hitop_659", "question_text": "Preferi ficar em casa do que ir a uma festa."},
    {"scale": "Social Anxiety", "item_code": "hitop_344", "question_text": "Senti-me tímido/a na presença de outras pessoas."},
    {"scale": "Social Anxiety", "item_code": "hitop_345", "question_text": "Tive dificuldade em manter o contacto ocular com as outras pessoas."},
    {"scale": "Social Anxiety", "item_code": "hitop_348", "question_text": "Fiquei desconfortável ao conhecer pessoas novas."},
    {"scale": "Social Anxiety", "item_code": "hitop_349", "question_text": "Evitei atuar ou dar uma palestra em frente dos outros."},
    {"scale": "Social Anxiety", "item_code": "hitop_355", "question_text": "Fiquei ansioso/a quando as outras pessoas me estavam a observar."},
    {"scale": "Somatic Preoccupation", "item_code": "hitop_491", "question_text": "Prestei bastante atenção às sensações do meu corpo."},
    {"scale": "Somatic Preoccupation", "item_code": "hitop_492", "question_text": "Notei pequenas mudanças na forma como o meu corpo se estava a sentir."},
    {"scale": "Somatic Preoccupation", "item_code": "hitop_493", "question_text": "Estive extremamente consciente do que se estava a passar com o meu corpo."},
    {"scale": "Somatic Preoccupation", "item_code": "hitop_494", "question_text": "Consegui sentir mudanças no meu corpo."},
    {"scale": "Somatic Preoccupation", "item_code": "hitop_498", "question_text": "Fui sensível às mudanças no meu corpo."},
    {"scale": "Specific Phobia (Animal-insect)", "item_code": "hitop_181", "question_text": "Tive medo de aranhas."},
    {"scale": "Specific Phobia (Animal-insect)", "item_code": "hitop_182", "question_text": "Tive medo de ratos ou ratazanas."},
    {"scale": "Specific Phobia (Animal-insect)", "item_code": "hitop_183", "question_text": "Tive medo de ser picado/a ou mordido/a por algum animal ou inseto."},
    {"scale": "Specific Phobia (Animal-insect)", "item_code": "hitop_184", "question_text": "Evitei zonas que pudessem ter cobras ou lagartos."},
    {"scale": "Specific Phobia (Animal-insect)", "item_code": "hitop_185", "question_text": "Ver um inseto (por exemplo, uma barata) perturbou-me."},
    {"scale": "Specific Phobia (Blood-Injection)", "item_code": "hitop_200", "question_text": "Ver algo ensanguentado deixou-me com tonturas."},
    {"scale": "Specific Phobia (Blood-Injection)", "item_code": "hitop_201", "question_text": "Ver uma agulha perturbou-me."},
    {"scale": "Specific Phobia (Blood-Injection)", "item_code": "hitop_202", "question_text": "Senti-me fraco/a ao ver sangue."},
    {"scale": "Specific Phobia (situational)", "item_code": "hitop_339", "question_text": "Tive medo de andar de avião."},
    {"scale": "Specific Phobia (situational)", "item_code": "hitop_340", "question_text": "Tive medo de alturas."},
    {"scale": "Specific Phobia (situational)", "item_code": "hitop_341", "question_text": "Fiquei muito ansioso/a durante uma tempestade."},
    {"scale": "Specific Phobia (situational)", "item_code": "hitop_342", "question_text": "Tive medo do escuro."},
    {"scale": "Submissiveness", "item_code": "exp26", "question_text": "Permiti que as pessoas se aproveitassem de mim."},
    {"scale": "Submissiveness", "item_code": "exp27", "question_text": "Tive dificuldade em defender-me."},
    {"scale": "Submissiveness", "item_code": "hitop_69", "question_text": "Tive dificuldade em me afirmar perante os outros."},
    {"scale": "Submissiveness", "item_code": "hitop_71", "question_text": "Os outros puderam aproveitar-se facilmente de mim por eu ser demasiado/a passivo/a e tímido/a."},
    {"scale": "Suicidality", "item_code": "hitop_356", "question_text": "Pensei muito sobre a morte."},
    {"scale": "Suicidality", "item_code": "hitop_358", "question_text": "Fiz um plano para me matar."},
    {"scale": "Suicidality", "item_code": "hitop_360", "question_text": "Pensei em matar-me."},
    {"scale": "Suicidality", "item_code": "hitop_361", "question_text": "Tentei matar-me."},
    {"scale": "Trauma Reactions", "item_code": "hitop_364", "question_text": "Evitei sítios que me recordassem de coisas más que aconteceram."},
    {"scale": "Trauma Reactions", "item_code": "hitop_365", "question_text": "Evitei pessoas que me podiam trazer más memórias."},
    {"scale": "Trauma Reactions", "item_code": "hitop_374", "question_text": "Tive memórias repetidas de um evento traumático."},
    {"scale": "Trauma Reactions", "item_code": "hitop_375", "question_text": "Assim do nada, senti como se um acontecimento traumático pelo qual passei estivesse a acontecer novamente."},
    {"scale": "Trauma Reactions", "item_code": "hitop_378", "question_text": "A minha mente foi inundada por imagens perturbadoras de uma má experiência."},
    {"scale": "Trichotillomania", "item_code": "hitop_383", "question_text": "Fiquei envergonhado(a) por ter arrancado o meu cabelo."},
    {"scale": "Trichotillomania", "item_code": "hitop_384", "question_text": "Em vários momentos, arranquei cabelos que tinham uma cor, textura ou comprimento diferentes dos outros."},
    {"scale": "Trichotillomania", "item_code": "hitop_385", "question_text": "Senti uma forte vontade de arrancar o meu cabelo."},
    {"scale": "Well-being", "item_code": "hitop_389", "question_text": "Tive orgulho de mim."},
    {"scale": "Well-being", "item_code": "hitop_392", "question_text": "Senti-me alegre."},
    {"scale": "Well-being", "item_code": "hitop_393", "question_text": "Senti-me otimista."},
    {"scale": "Well-being", "item_code": "hitop_395", "question_text": "Senti-me bem comigo próprio/a."},
    {"scale": "Well-being", "item_code": "hitop_632", "question_text": "Senti-me motivado/a."},
    {"scale": "Workaholism", "item_code": "ext_131", "question_text": "Pode-se dizer que, de certa forma, fui viciado/a em trabalho."},
    {"scale": "Workaholism", "item_code": "ext_278", "question_text": "Mesmo em dias de folga, dei por mim a pensar sobre o trabalho."},
    {"scale": "Workaholism", "item_code": "ext_371", "question_text": "Estive tão focado(a) em ser produtivo(a) que acabei por ter menos tempo para os amigos e a família."},
    {"scale": "Workaholism", "item_code": "ext_397", "question_text": "O meu sucesso profissional foi o aspeto mais importante da minha vida."},
    {"scale": "Workaholism", "item_code": "ext_99", "question_text": "As pessoas disseram-me que trabalho demasiado."},
    {"scale": "Craving", "item_code": "sud012", "question_text": "Ver coisas que me lembravam de substâncias (como álcool, nicotina, drogas ilícitas, medicamentos fora da indicação médica) despertou em mim uma forte vontade ou desejo de consumir."},
    {"scale": "Craving", "item_code": "sud018", "question_text": "Pensei sobre consumir (álcool, nicotina, drogas ilícitas, medicamentos fora da indicação médica)"},
    {"scale": "Craving", "item_code": "sud020", "question_text": "Desejei ou ansiei intensamente consumir uma ou mais substâncias (como álcool, nicotina, drogas ilícitas, medicamentos fora da indicação médica, etc)."},
    {"scale": "Craving", "item_code": "sud013", "question_text": "Filmes, imagens ou músicas que mostrassem o uso de substâncias deram-me um forte desejo ou vontade de consumir."},
    {"scale": "Craving", "item_code": "exp30", "question_text": "Tive desejos intensos de consumir (por exemplo, álcool, nicotina, drogas ilícitas, medicamentos fora da indicação médica)."},
    {"scale": "Craving", "item_code": "exp31", "question_text": "Senti que nada seria melhor do que consumir (álcool, nicotina, drogas ilícitas, medicamentos fora da indicação médica ou outras substâncias)."},
    {"scale": "Craving", "item_code": "exp32", "question_text": "Tive uma forte vontade para consumir (álcool, nicotina, drogas ilícitas, medicamentos fora da indicação médica)"},
    {"scale": "Hazardous Use", "item_code": "sud040", "question_text": "Conduzi um veículo quando estava sob a influência de substâncias (álcool, nicotina, drogas ilícitas, medicamentos fora da indicação médica)"},
    {"scale": "Hazardous Use", "item_code": "sud041", "question_text": "Quando estive sob a influência de substâncias (por exemplo, álcool, nicotina, drogas ilícitas, medicamentos fora da indicação médica, etc), coloquei-me numa situação em que poderia ter-me magoado (por exemplo, andar de bicicleta, nadar ou operar máquinas pesadas)."},
    {"scale": "Hazardous Use", "item_code": "sud043", "question_text": "Danifiquei algo valioso quando estava sob a influência de substâncias (álcool, nicotina, drogas ilícitas, medicamentos fora da indicação médica)"},
    {"scale": "Hazardous Use", "item_code": "sud044", "question_text": "Quando consumi (álcool, nicotina, drogas ilícitas, medicamentos fora da indicação médica), fiz coisas arriscadas ou perigosas que não faria se estivesse sóbrio(a)."},
    {"scale": "Impaired Control", "item_code": "sud058", "question_text": "Não fui capaz de reduzir a quantidade de consumo (álcool, nicotina, drogas ilícitas, medicamentos fora da indicação médica)  quando queria."},
    {"scale": "Impaired Control", "item_code": "sud084", "question_text": "Consumi substâncias em excesso (álcool, nicotina, drogas ilícitas, medicamentos fora da indicação médica)."},
    {"scale": "Impaired Control", "item_code": "sud096", "question_text": "Tentei consumir substâncias (álcool, nicotina, drogas ilícitas, medicamentos fora da indicação médica) apenas em certos momentos, mas isso não funcionou durante muito tempo."},
    {"scale": "Impaired Control", "item_code": "sud100", "question_text": "Fiquei embriegado(a), ganzado(a) ou mocado(a), embora tivesse decidido previamente que não o iria fazer."},
    {"scale": "Impaired Control", "item_code": "sud035", "question_text": "Continuei a consumir (álcool, nicotina, drogas ilícitas, medicamentos fora da indicação médica) apesar de isso prejudicar o meu desempenho no trabalho, escola ou outras atividades."},
    {"scale": "Impaired Control", "item_code": "sud047", "question_text": "Consumir (álcool, nicotina, drogas ilícitas, medicamentos fora da indicação médica), ou sentir-me indisposto devido a este consumo, impediu-me de cuidar de mim, da minha casa ou da minha família."},
    {"scale": "Impaired Control", "item_code": "sud049", "question_text": "Faltei ao trabalho, à escola ou a outras obrigações por estar a recuperar dos efeitos de ter consumido substâncias (ex.: ressaca, efeitos físicos ou psicológicos)."},
    {"scale": "Impaired Control", "item_code": "exp33", "question_text": "Consumir (álcool, nicotina, drogas ilícitas ou medicamentos fora da indicação médica) interferiu com as minhas relações."},
    {"scale": "Tolerance", "item_code": "sud070", "question_text": "Com o tempo, precisei de aumentar a quantidade do que consumia (por exemplo, álcool, nicotina, drogas ilícitas ou medicamentos fora da indicação médica) para sentir o mesmo efeito."},
    {"scale": "Tolerance", "item_code": "sud071", "question_text": "Consumi (álcool, nicotina, drogas ilícitas, medicamentos fora da indicação médica ou outras substâncias) numa quantidade significativa, antes que as outras pessoas se apercebessem de que eu tinha consumido."},
    {"scale": "Tolerance", "item_code": "sud072", "question_text": "Precisei de consumir muito mais - por exemplo, álcool, nicotina, drogas ilícitas, medicamentos fora da indicação médica - do que as outras pessoas para sentir algum efeito."},
    {"scale": "Withdrawal", "item_code": "exp28", "question_text": "Ao deixar ou reduzir o consumo de substâncias (ex: álcool, nicotina, drogas ilícitas, medicamentos fora da indicação médica, etc) tive sintomas físicos no meu corpo como suores, tremores, náuseas, diarreia, alterações do apetite, dores corporais, alterações do sono ou mal-estar geral."},
    {"scale": "Withdrawal", "item_code": "exp29", "question_text": "Ao deixar ou reduzir o consumo de substâncias (ex: álcool, nicotina, drogas ilícitas, medicamentos fora da indicação médica, etc) tive sintomas como nervosismo, tristeza, irritabilidade, agitação, pensamento lento ou confuso, dificuldade de concentração ou alterações percetivas."},
    {"scale": "Catch", "item_code": "catch_6", "question_text": "A capital de Portugal é Lisboa. Por favor, selecione \"Nada\"."},
    {"scale": "Catch", "item_code": "catch_7", "question_text": "Para confirmar que está a ler com atenção, por favor selecione \"Muito\" nesta afirmação."}
]

for q in questions_data:
    scale_obj = scale[q["scale"]]

    question_obj, created = Question.objects.get_or_create(
        scale=scale_obj,
        item_code=q["item_code"],
        question_text=q["question_text"]
    )

print(f"{len(questions_data)} perguntas criadas com sucesso!")