# Generated by Django 6.0.1 on 2026-03-04 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='area_formacao',
            field=models.CharField(choices=[('Psicologia', 'Psicologia'), ('Medicina', 'Medicina'), ('Outros', 'Outros')], default='Psicologia', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userprofile',
            name='cedula_profissional',
            field=models.CharField(default='0000', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userprofile',
            name='objetivo_uso',
            field=models.CharField(choices=[('clinico', 'Avaliação em contexto clínico'), ('forense', 'Avaliação em contexto forense'), ('investigacao', 'Avaliação em contexto de investigação')], default='clinico', max_length=50),
            preserve_default=False,
        ),
    ]
