# Generated by Django 6.0.1 on 2026-03-19 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
        ('website', '0003_userprofile_area_formacao_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='spectra',
            field=models.ManyToManyField(blank=True, related_name='user_profiles', to='polls.spectra'),
        ),
    ]
