# Generated by Django 6.0.1 on 2026-03-26 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_userprofile_spectra'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='questionnaire_completed',
            field=models.BooleanField(default=False),
        ),
    ]
