# Generated by Django 6.0.1 on 2026-06-09 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_userprofile_questionnaire_completed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='questionnaire_completed',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='spectra',
        ),
    ]
