# Generated by Django 6.0.1 on 2026-09-13

from django.db import migrations, models


def mark_existing_professionals_as_verified(apps, schema_editor):
    UserProfile = apps.get_model("website", "UserProfile")
    UserProfile.objects.filter(user_type="professional").update(is_verified=True)


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0006_remove_userprofile_questionnaire_completed_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="is_verified",
            field=models.BooleanField(default=False, verbose_name="Verificado"),
        ),
        migrations.RunPython(
            mark_existing_professionals_as_verified,
            migrations.RunPython.noop,
        ),
    ]
