# Generated by Django 6.0.1 on 2026-09-13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0007_userprofile_is_verified"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Record",
        ),
    ]
