# Generated by Django 6.0.1 on 2026-09-21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0008_delete_record"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="archived_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
