# Generated by Django 6.0.1 on 2026-04-26 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_questionnairesubmission_useranswer_submission'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionnairesubmission',
            name='is_open',
            field=models.BooleanField(default=True),
        ),
    ]
