# Generated by Django 6.0.1 on 2026-05-06 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0005_dynamicquestion_questioncategory_dynamicchoice_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dynamicquestion',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
