# Generated by Django 6.0.1 on 2026-06-02 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0006_dynamicquestion_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionnairesubmission',
            name='spectra',
            field=models.ManyToManyField(blank=True, to='polls.spectra'),
        ),
        migrations.AddField(
            model_name='questionnairesubmission',
            name='title',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
