# Generated by Django 6.0.1 on 2026-06-02 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0007_questionnairesubmission_spectra_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionnairesubmission',
            name='access_token',
            field=models.UUIDField(blank=True, null=True),
        ),
    ]
