# Generated by Django 6.0.1 on 2026-06-02 15:23

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0008_questionnairesubmission_access_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionnairesubmission',
            name='access_token',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
