# Generated by Django 6.0.1 on 2026-06-11 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0009_alter_questionnairesubmission_access_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sociodemographicanswer',
            name='answer_value',
            field=models.CharField(max_length=255),
        ),
    ]
