# Generated by Django 6.0.1 on 2026-07-20 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0010_alter_sociodemographicanswer_answer_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionnairesubmission',
            name='simulation_mode',
            field=models.CharField(choices=[('normal', 'Normal'), ('simulated', 'Simulada'), ('simulated_nulls', 'Simulada com omissões')], default='normal', max_length=20),
        ),
    ]
