# Generated by Django 6.0.1 on 2026-07-20 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0011_questionnairesubmission_simulation_mode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionnairesubmission',
            name='simulation_mode',
            field=models.CharField(choices=[('normal', 'Aplicação normal'), ('simulated', 'Simular respostas'), ('simulated_nulls', 'Simular respostas com omissões')], default='normal', max_length=20),
        ),
        migrations.AlterField(
            model_name='useranswer',
            name='answer',
            field=models.CharField(choices=[('1', 'Nunca'), ('2', 'Raramente'), ('3', 'Às vezes'), ('4', 'Sempre'), ('5', 'Não sei / Prefiro não responder')], max_length=1),
        ),
    ]
