# Generated by Django 6.0.1 on 2026-08-02 20:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0013_normativeparticipant_normativeanswer'),
    ]

    operations = [
        migrations.CreateModel(
            name='NormativeScaleScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raw_score', models.FloatField()),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scale_scores', to='polls.normativeparticipant')),
                ('scale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.scale')),
            ],
            options={
                'unique_together': {('participant', 'scale')},
            },
        ),
    ]
