# Generated by Django 6.0.1 on 2026-08-19 13:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0014_normativescalescore'),
    ]

    operations = [
        migrations.CreateModel(
            name='NormativeSpectrumScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raw_score', models.FloatField()),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spectrum_scores', to='polls.normativeparticipant')),
                ('spectrum', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.spectra')),
            ],
            options={
                'unique_together': {('participant', 'spectrum')},
            },
        ),
    ]
