# Generated by Django 6.0.1 on 2026-08-26 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0015_normativespectrumscore'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='expected_answer',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='question',
            name='is_attention_check',
            field=models.BooleanField(default=False),
        ),
    ]
