# Generated by Django 6.0.1 on 2026-08-26 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0016_question_expected_answer_question_is_attention_check'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='expected_answer',
            field=models.CharField(blank=True, default='', max_length=1),
        ),
    ]
