# Generated by Django 6.0.1 on 2026-09-17 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0017_alter_question_expected_answer'),
    ]

    operations = [
        migrations.AddField(
            model_name='dynamicquestion',
            name='section',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='dynamicquestion',
            name='show_if_question',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='dynamicquestion',
            name='show_if_values',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
