# Generated by Django 6.0.1 on 2026-09-17 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0019_questionnairesubmission_sociodemographic_completed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dynamicchoice',
            name='label',
            field=models.TextField(),
        ),
    ]
