# Generated by Django 6.0.1 on 2026-09-17 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0020_alter_dynamicchoice_label'),
    ]

    operations = [
        migrations.AddField(
            model_name='dynamicquestion',
            name='group_intro',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='questionnairesubmission',
            name='sociodemographic_step',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
