# Generated by Django 6.0.1 on 2026-09-21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("polls", "0022_dynamicquestion_is_active"),
    ]

    operations = [
        migrations.AddField(
            model_name="questionnairesubmission",
            name="normative_exported_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="questionnairesubmission",
            name="normative_status",
            field=models.CharField(
                choices=[
                    ("pending", "Pendente"),
                    ("ineligible", "Não elegível"),
                    ("exported", "Exportada"),
                ],
                default="pending",
                max_length=10,
            ),
        ),
    ]
