# Generated by Django 6.0.1 on 2026-09-23 15:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0026_questionnairesubmission_is_test_data'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='normativedatasetversion',
            name='polls_one_active_normative_version',
        ),
        migrations.AddField(
            model_name='normativedatasetversion',
            name='baseline_version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='test_derivatives', to='polls.normativedatasetversion'),
        ),
        migrations.AddField(
            model_name='normativedatasetversion',
            name='environment',
            field=models.CharField(choices=[('production', 'Produção'), ('test', 'Teste')], db_index=True, default='production', max_length=12),
        ),
        migrations.AddField(
            model_name='normativeparticipant',
            name='source',
            field=models.CharField(choices=[('real', 'Real'), ('synthetic', 'Sintético')], db_index=True, default='real', max_length=12),
        ),
        migrations.AddField(
            model_name='normativeparticipant',
            name='source_submission',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='synthetic_normative_participant', to='polls.questionnairesubmission'),
        ),
        migrations.AddConstraint(
            model_name='normativedatasetversion',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'active')), fields=('environment',), name='polls_one_active_normative_version_per_environment'),
        ),
    ]
